AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3
  Exclude:
    - spec/dummy/db/schema.rb
    - bin/**/*

Rails:
  Enabled: true

# We have better monitors these days.
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'
